import { chromium } from 'playwright-core'

const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true })
const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } })
const errors = []
page.on('dialog', dialog => dialog.accept('demo123'))
page.on('pageerror', error => errors.push(error.message))
page.on('response', response => { if (response.url().includes('/api/') && response.status() >= 400) errors.push(`${response.status()} ${response.url()}`) })
await page.goto('http://127.0.0.1:5173/')
const frame = page.frameLocator('iframe[title="Digital Passport"]')
await frame.getByRole('button', { name: /Технический заказчик/ }).click()
const app = page.frame({ url: /passport\.html/ })
await frame.locator('.project-card').first().waitFor()
const sampleId = await app.evaluate(() => projectMeta.find(meta => meta.name === 'Телеграф · образец IFC')?.id)
if (!sampleId) throw Error('Sample IFC project missing')
await app.evaluate(id => switchProject(id), sampleId)
await frame.locator('#projectModelFrame').waitFor()
await frame.locator('#projectModelRows .row').first().waitFor({ timeout: 120000 })
const viewer = frame.frameLocator('#projectModelFrame')
await viewer.locator('#status').filter({ hasText: /Показано/ }).waitFor({ timeout: 240000 })
const count = await app.evaluate(() => modelIndex.length)
const rendered = await viewer.locator('#status').textContent()
await frame.locator('#projectModelRows .row button').first().click()
const isolated = await app.evaluate(() => modelIsolated)
await frame.getByRole('button', { name: 'Показать всю модель' }).click()
const all = await app.evaluate(() => modelIsolated)
await frame.getByRole('button', { name: 'Скрыть модель' }).click()
const hidden = await app.evaluate(() => modelVisible)
await frame.getByRole('button', { name: 'Показать модель' }).click()
const visible = await app.evaluate(() => modelVisible)
console.log(JSON.stringify({ count, rendered, isolated, all, hidden, visible, errors }))
await browser.close()
