import { chromium } from 'playwright-core'

const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('dialog', dialog => dialog.accept('demo123'))
const errors = []
page.on('pageerror', error => errors.push(error.message))
page.on('response', response => { if (response.url().includes('/api/') && response.status() >= 400) errors.push(`${response.status()} ${response.url()}`) })
await page.goto('http://127.0.0.1:5173/')
const frame = page.frameLocator('iframe')
await frame.getByRole('button', { name: /Технический заказчик/ }).click()
await frame.locator('.project-card').first().waitFor()
const projects = await frame.locator('.project-card').count()
const app = page.frame({ url: /passport\.html/ })
await app.evaluate(() => go('passport'))
await app.evaluate(() => qr())
const qrVisible = await frame.locator('dialog[open] svg').count()
await frame.locator('dialog[open] button[aria-label="Закрыть"]').click()
await app.evaluate(() => login())
await frame.getByRole('button', { name: /Представитель завода/ }).click()
await frame.locator('.sidebar').waitFor()
await app.evaluate(() => switchProject('PR-026'))
await page.waitForTimeout(500)
const factoryVisible = await frame.locator('.sidebar').innerText()
console.log(JSON.stringify({ projects, qrVisible, factoryVisible: factoryVisible.includes('Входящие заказы'), errors }))
await browser.close()
