import { chromium } from 'playwright-core'

const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('dialog', dialog => dialog.accept('demo123'))
page.on('pageerror', error => errors.push(error.message))
await page.goto('http://127.0.0.1:5173/')
const frame = page.frameLocator('iframe[title="Digital Passport"]')
await frame.getByRole('button', { name: /Технический заказчик/ }).click()
await frame.locator('.project-card').first().waitFor()
const app = page.frame({ url: /passport\.html/ })
await app.evaluate(() => switchProject(projectMeta.find(meta => meta.name === '\u0422\u0435\u043b\u0435\u0433\u0440\u0430\u0444 \u00b7 \u043e\u0431\u0440\u0430\u0437\u0435\u0446 IFC')?.id))
await app.evaluate(() => go('registry'))
const registry = await frame.locator('#itemsTable').innerText()
await app.evaluate(() => newOrder())
const orderExists = await frame.locator('#orderItems').count()
let chosen = null
if (orderExists) {
  await frame.locator('#orderSearch').fill('несуществующий')
  const filteredEmpty = await frame.locator('#orderPager').innerText()
  await frame.locator('#orderSearch').fill('КН-')
  await frame.getByRole('button', { name: 'Выбрать все отфильтрованные' }).click()
  chosen = await frame.locator('#orderItems input:checked').count()
  if (!filteredEmpty.includes('Найдено: 0')) errors.push('Order filter failed')
  await frame.locator('dialog[open] button[aria-label="Закрыть"]').click()
} else await frame.locator('dialog[open] button[aria-label="Закрыть"]').click()
await app.evaluate(() => go('acceptance'))
const disabled = await frame.locator('button:has-text("Принять / проверить качество"):disabled').count()
const hint = await frame.locator('[id^="accept-hint-"]').count()
await app.evaluate(() => showIfcReport({ schema: 'IFC4', counts: { COLUMN: 45 }, fileId: 'test', elements: Array.from({ length: 45 }, (_, index) => ({ globalId: `TEST${index}`, expressId: String(index + 1), type: 'COLUMN', name: index < 4 ? 'Марка A' : 'Марка B', floor: 'Этаж 1' })) }, 'test.ifc'))
await frame.locator('#ifcSearch').fill('Марка A')
await frame.getByRole('button', { name: 'Выбрать видимые' }).click()
const importSelected = await frame.locator('#ifcRows input:checked').count()
const importPager = await frame.locator('#ifcPager').innerText()
await frame.locator('#ifcSearch').fill('')
await frame.getByRole('button', { name: 'Выбрать видимые' }).click()
const importAllPages = await frame.locator('#ifcRows input:checked').count()
await frame.locator('dialog[open] button[aria-label="Закрыть"]').click()
console.log(JSON.stringify({ registry: registry.includes('КН-'), orderExists: !!orderExists, chosen, disabled, hint, importSelected, importAllPages, importPager, errors }))
await browser.close()
